'use strict';

const { DataTypes } = require('sequelize');

/**
 * CalendarEvent Model
 *
 * A single injection event on the calendar.
 * Generated by the schedule engine for every day a peptide should be taken.
 *
 * Pre-computing all events means the mobile app can query
 * "all events for user X on date Y" without any runtime calculation.
 * Events are wiped and regenerated whenever the schedule changes.
 */
module.exports = (sequelize) => {
  const CalendarEvent = sequelize.define(
    'CalendarEvent',
    {
      id: {
        type:         DataTypes.UUID,
        defaultValue: DataTypes.UUIDV4,
        primaryKey:   true,
      },

      scheduleId: {
        type:       DataTypes.UUID,
        allowNull:  false,
        field:      'schedule_id',
        references: { model: 'user_schedules', key: 'id' },
        onDelete:   'CASCADE',
      },

      scheduleItemId: {
        type:       DataTypes.UUID,
        allowNull:  false,
        field:      'schedule_item_id',
        references: { model: 'schedule_items', key: 'id' },
        onDelete:   'CASCADE',
      },

      peptideId: {
        type:       DataTypes.UUID,
        allowNull:  false,
        field:      'peptide_id',
        references: { model: 'peptides', key: 'id' },
      },

      // Calendar date of this injection (YYYY-MM-DD)
      eventDate: {
        type:      DataTypes.DATEONLY,
        allowNull: false,
        field:     'event_date',
      },

      // "AM" | "PM" | "BOTH" | "MIDDAY"
      timeOfDay: {
        type:         DataTypes.ENUM('AM', 'PM', 'BOTH', 'MIDDAY'),
        allowNull:    false,
        defaultValue: 'AM',
        field:        'time_of_day',
      },

      // Dose in syringe units for this day (respects escalation)
      doseUnits: {
        type:      DataTypes.FLOAT,
        allowNull: false,
        field:     'dose_units',
      },

      // Human-readable dose label, e.g. "200 mcg (0.2 mg)"
      doseLabel: {
        type:      DataTypes.STRING(100),
        allowNull: true,
        field:     'dose_label',
      },

      // Which escalation step this event belongs to (1-based).
      // Null for overridden (flat-dose) schedules.
      escalationStep: {
        type:      DataTypes.INTEGER,
        allowNull: true,
        field:     'escalation_step',
      },

      // True if this is a rest day (peptide is paused this week)
      isRestDay: {
        type:         DataTypes.BOOLEAN,
        allowNull:    false,
        defaultValue: false,
        field:        'is_rest_day',
      },

      // True once the user has logged this injection as done
      isCompleted: {
        type:         DataTypes.BOOLEAN,
        allowNull:    false,
        defaultValue: false,
        field:        'is_completed',
      },

      completedAt: {
        type:      DataTypes.DATE,
        allowNull: true,
        field:     'completed_at',
      },
    },
    {
      tableName:   'calendar_events',
      underscored: true,
      indexes: [
        // Primary query: all events for a schedule on a given date
        { fields: ['schedule_id', 'event_date'] },
        { fields: ['schedule_item_id'] },
        { fields: ['peptide_id'] },
        { fields: ['event_date'] },
        // Supports "show me today's injections across all my schedules"
        { fields: ['schedule_id', 'is_completed', 'event_date'] },
      ],
    }
  );

  CalendarEvent.associate = (models) => {
    CalendarEvent.belongsTo(models.UserSchedule, {
      foreignKey: 'schedule_id',
      as:         'schedule',
    });

    CalendarEvent.belongsTo(models.ScheduleItem, {
      foreignKey: 'schedule_item_id',
      as:         'scheduleItem',
    });

    CalendarEvent.belongsTo(models.Peptide, {
      foreignKey: 'peptide_id',
      as:         'peptide',
    });
  };

  return CalendarEvent;
};
