'use strict';

const PDFDocument = require('pdfkit');
const dayjs       = require('dayjs');

/**
 * @param {object} params
 * @param {object} params.groupedEvents   Output of scheduleEngine.groupEventsByMonth()
 * @param {string} params.scheduleName    User's schedule name
 * @param {string} params.userName        User's first + last name
 * @param {string[]} params.months        Array of "YYYY-MM" strings to include (all if omitted)
 * @returns {PDFDocument}                 Pipe this to res or a file stream
 *
 * Usage:
 *   const doc = generateCalendarPdf({ groupedEvents, scheduleName, userName });
 *   res.setHeader('Content-Type', 'application/pdf');
 *   doc.pipe(res);
 *   doc.end();
 */
function generateCalendarPdf({ groupedEvents, scheduleName = 'Peptide Schedule', userName = '', months }) {
  const doc = new PDFDocument({
    size:    'LETTER',   // 8.5" × 11"
    margins: { top: 40, bottom: 40, left: 36, right: 36 },
    info: {
      Title:   `${scheduleName} — Peptide Calendar`,
      Author:  'PeptideDosage.com',
      Subject: 'Personalized Peptide Dosing Schedule',
    },
  });

  const COLORS = {
    headerBg:    '#3B2D8F',   // deep purple
    headerText:  '#FFFFFF',
    dayHeader:   '#2C2C2C',
    gridLine:    '#E0E0E0',
    amChip:      '#4CAF50',   // green
    pmChip:      '#2196F3',   // blue
    restChip:    '#9E9E9E',   // grey
    eventText:   '#212121',
    restText:    '#757575',
    footerText:  '#9E9E9E',
    pageNumbers: '#555555',
    todayBg:     '#FFF9C4',
  };

  const PAGE_W = doc.page.width  - 72; // usable width (margins)
  const COL_W  = PAGE_W / 7;
  const ROW_H  = 95;
  const HEADER_H = 80;

  const sortedMonths = months
    ? months.sort()
    : Object.keys(groupedEvents).sort();

  sortedMonths.forEach((monthKey, pageIndex) => {
    if (pageIndex > 0) doc.addPage();

    const monthEvents = groupedEvents[monthKey] || {};
    const monthStart  = dayjs(`${monthKey}-01`);
    const monthName   = monthStart.format('MMMM YYYY');

    doc.rect(36, 40, PAGE_W, HEADER_H).fill(COLORS.headerBg);

    doc
      .fillColor(COLORS.headerText)
      .fontSize(22)
      .font('Helvetica-Bold')
      .text(monthName, 36, 58, { width: PAGE_W, align: 'center' });

    doc
      .fontSize(10)
      .font('Helvetica')
      .text(`${scheduleName}${userName ? ` — ${userName}` : ''}`, 36, 86, { width: PAGE_W, align: 'center' });

    const DAY_LABELS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    const gridTop    = 40 + HEADER_H + 4;

    doc.fillColor(COLORS.dayHeader).fontSize(9).font('Helvetica-Bold');
    DAY_LABELS.forEach((label, i) => {
      doc.text(label, 36 + i * COL_W, gridTop, { width: COL_W, align: 'center' });
    });

    const firstDayOfWeek = monthStart.day(); // 0=Sun
    const daysInMonth    = monthStart.daysInMonth();
    const rows           = Math.ceil((firstDayOfWeek + daysInMonth) / 7);

    let cellTop = gridTop + 16;

    for (let row = 0; row < rows; row++) {
      for (let col = 0; col < 7; col++) {
        const dayNum = row * 7 + col - firstDayOfWeek + 1;
        if (dayNum < 1 || dayNum > daysInMonth) continue;

        const cellX    = 36 + col * COL_W;
        const cellY    = cellTop + row * ROW_H;
        const dateStr  = monthStart.date(dayNum).format('YYYY-MM-DD');
        const dayEvts  = monthEvents[dateStr] || [];

        // Cell border
        doc
          .rect(cellX, cellY, COL_W - 2, ROW_H - 2)
          .strokeColor(COLORS.gridLine)
          .lineWidth(0.5)
          .stroke();

        // Day number
        doc
          .fillColor(COLORS.dayHeader)
          .fontSize(9)
          .font('Helvetica-Bold')
          .text(String(dayNum), cellX + 3, cellY + 3, { width: COL_W - 6 });

        // Events for this day (limit to 3 visible to avoid overflow)
        const visibleEvts = dayEvts.slice(0, 3);
        visibleEvts.forEach((evt, evtIdx) => {
          const evtY = cellY + 16 + evtIdx * 22;

          if (evt.isRestDay) {
            _drawChip(doc, cellX + 3, evtY, COL_W - 8, 'REST', COLORS.restChip, '#FFFFFF');
            return;
          }

          const chipColor = evt.timeOfDay === 'PM' ? COLORS.pmChip : COLORS.amChip;
          const label     = `${evt.peptide?.name || 'Peptide'} ${evt.doseUnits}u`;
          _drawChip(doc, cellX + 3, evtY, COL_W - 8, label, chipColor, '#FFFFFF');
        });

        if (dayEvts.length > 3) {
          doc
            .fillColor(COLORS.restText)
            .fontSize(7)
            .font('Helvetica')
            .text(`+${dayEvts.length - 3} more`, cellX + 3, cellY + ROW_H - 14, { width: COL_W - 6 });
        }
      }
    }

    const footerY = doc.page.height - 30;
    doc
      .fillColor(COLORS.footerText)
      .fontSize(8)
      .font('Helvetica')
      .text('Generated by PeptideDosage.com  |  For research purposes only', 36, footerY, {
        width: PAGE_W,
        align: 'center',
      });
  });

  return doc;
}


/**
 * Draw a small colored chip / badge with text.
 */
function _drawChip(doc, x, y, width, text, bgColor, textColor) {
  const h = 14;
  doc.rect(x, y, width, h).fill(bgColor);
  doc
    .fillColor(textColor)
    .fontSize(6.5)
    .font('Helvetica-Bold')
    .text(text, x + 2, y + 3, { width: width - 4, ellipsis: true });
}

module.exports = { generateCalendarPdf };
